name: First_Django_CI

# this is your trigger or event that will start the workflow.
on :
  push:
    branches: [ main ]
  
jobs : 
  build : 
    runs-on : ubuntu-latest
    steps : 
      - name : say hello
        run : echo "hello world!"